import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

// USE REACT ICONS
// USE ZOD + REACT HOOK FORM
// USE NEXT 

// Import Modules
import { Chakra } from '@/providers/chakra'

// Import Components
import Nav from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Chakra>
          <Nav />
          {children}
        </Chakra>
      </body>
    </html>
  )
}
